# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe891f67431f7dc0e3179c3c614577395d9f23b28f80917520d1165a6f977db6231c434b7729187a3485022438f8043209b1c6a48886ce3847f53f68cdc36cb

test:
  secret_key_base: cd5c25b4cf36a1cfcbab0730f09a2ccbd8a514f00daeecc75cd31671b2946f61861c78a02bfd965fdf02ca349ff5f35320cfd86d12ba06bec53482ce250af8cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
